version: 2
jobs:
  build:
    docker:
      - image: andersonopt/hugo

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote


      - run:
          name: Print the Current Time
          command: date

      - run:
          name: Hugo build
          command: hugo

      - run: 
          name: List output
          command: ls public/

      - run:
          name: AWS Sync
          command: aws s3 sync public s3://meetmeinthemountains.com/ -acl public-read